controller:
    private_key: ENC[AES256_GCM,data:RNKx03IT7GO92Y2+Qmah8Iu7DsgxPHqVIVCWNX2vLVmN1JMnwQqLNtMXyIQ=,iv:73fu7UDm00Kqs4YaZNuaHym+yu6276m2cdafe704M6A=,tag:wNvWt9KIunbm6HAMULVmIA==,type:str]
    public_key: ENC[AES256_GCM,data:w0GqJujLnuDT9qQv+QDCYJt0OEKyiQXmBUYXQv0c8yBVS2r+VojgDXVjJ6U=,iv:PRDpqhYzZg2lqr5h5rRMDJB2ExTCZuPgV7mc9B5sS2A=,tag:chMo2+i7lJ+v8tpDkD/ejQ==,type:str]
saconsole:
    private_key: ENC[AES256_GCM,data:x4G4WXRFl/godCGO+n9/uCxkoeg6HJ82/C2pLk2sSiI5eRbeNlbY/Y/4+no=,iv:U7kMHihJ5VKjqpreaT84czFTKz8enseLnZXDEFY3qpc=,tag:QCd56qlV/TiEV7S++Wb57w==,type:str]
    public_key: ENC[AES256_GCM,data:V1eNjicWswwoeUF7igF3go74sLlRQYfM8sVyUctOgdmHA3jTkPhdNnsxMtY=,iv:3JrFjT4C/tfSFllzwmuY2AOHbWjrdN4rdAYoFI1ZKEY=,tag:Vcg2gocVXyZmRZPVPvy9aw==,type:str]
dev03:
    private_key: ENC[AES256_GCM,data:oIN7w83T72xCEMpoOuxCpzwCw09VqW29gTWEul1NB9J54oKU5cacIYjZeSs=,iv:cxFXwnFqtGp4JkUJfVlIGN9r//FvRu1l1L9+TQ5DiE8=,tag:2I24Sctkt86sNKIp/34Vqw==,type:str]
    public_key: ENC[AES256_GCM,data:GUqQSEztvPSS83obbUNzwjkF+rJQmaKyUZPY2IVoe63G0eCfMcz8Z84860o=,iv:e+0/SsFBGEyAloOVlXrYUuLRClZgU0DJyP4W6Rj4/Jc=,tag:tWe3v3z8ujxHZ/ZLmH/Q2A==,type:str]
dev02:
    private_key: ENC[AES256_GCM,data:+aoFzyfEFabONTZZ8I1cBkrNS/RlJeXxIIPxjP5OlgLylW9GH4LlGnTo8lM=,iv:cYsV/ie+pvQTE/aZJlUndq1CuG/3c+YxqwMLDFT9zXs=,tag:NLqMOA8TRpXdbjeA/F9nug==,type:str]
    public_key: ENC[AES256_GCM,data:+8CjLI2YUJSNuTP74UWRqOUbHt6PIlNuG9uIvXPnbd9d072RT/5XZSjRw8E=,iv:EPp38ESFk85GcrxnfNLYzgxDkG3Z5Qv8XN588M7+2SI=,tag:Pwpu/hpwPU4kV4vPyOX5AQ==,type:str]
dev01:
    private_key: ENC[AES256_GCM,data:Luyo4WsPLbKURdna1jOHioqhEwsn2VQefcKmU5ZzXPErqtNSbRZH5Q5vN5w=,iv:f0gfM1KQwLgII9lERIf7NruA+9YGg3Gzngg3yqHCxsw=,tag:mdKfRaJw29SqUIQqHWlYiA==,type:str]
    public_key: ENC[AES256_GCM,data:0AsK272R+/ZJOysXK4BrbmBoZj2tbACDz58689+CfuBBGGpqrUK1iejYL5E=,iv:Yd2FYoqsZuUab4r673cBXbyK27pz1t9aX0US0mUaGac=,tag:Iqsn6VFrnVvBq9WdoMNnXA==,type:str]
preshared_keys:
    controller_saconsole: ENC[AES256_GCM,data:93r8+z/iGKlBo3NdOBqxnhnHQWmy4B08X/V4PHGn+AbsxJzzkGPJwsBisIQ=,iv:aPQrvaexW9aYGjtJlci0VpoY2M7H+9XVKcfzuSp9mpY=,tag:6RQyfhI7rKJekiAsIdGxCg==,type:str]
    dev03_saconsole: ENC[AES256_GCM,data:7afpcayeq7bcFKlarrzkqVF86TSbsjnBQxU2ySxU/kSLKsRROWsWggZnjMs=,iv:gI3uufgsKr4PYSAKdmn1S6GXnuKRWt+WBDTJAH2Hqy0=,tag:OGl90wrtDicBTHFhu5mFbw==,type:str]
    dev02_saconsole: ENC[AES256_GCM,data:Gpd/zR4HM/ZG2CMTwjbWGHHZyQjzYcjQt39ZXd8x/rqvNr5PXpP2Oe289A8=,iv:01LKIbmno5E7xronZ4aIK3mppA97pMkzz6VZx6c+0Hw=,tag:uxalefaFoL/74dWyxy8RsA==,type:str]
    dev01_saconsole: ENC[AES256_GCM,data:rdxw/r9/49TBAIWzlHI6DCe9VD6Eql0L/wrFqOl1payUxMXG38krjTbwHM0=,iv:KtrjegcmPPukTV/tfq8ktjgMOF+ZILJSrmvxJ8AY2B8=,tag:RuAu3n5yzD8BKf+1lo2uOg==,type:str]
sops:
    age:
        - recipient: age185wy6suru3x53leqjf866zsz02vece8cnsy6g92tz7ae0ykw45dsjp2sl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVlZ0a1BRdFd0NG1vNGNa
            T0xqOUZzWUdSQldzNXdUSm02RDlzUzJGTTJ3CkZBM3ZRNnFpSGJ4OEdMM3pJK0tU
            WGNWelRZbmlYbmVmVWJZMjdWNGdEelUKLS0tICtjZzEyZ2hEYnYvWTI4MWFoUFJJ
            eC9XRkVWVVNhM1VManhpUG9RbzFEMHcKj2wO9ziJFxpHSCwpF5Afb2D9K0+C1+qz
            J8aXpc/3v12TVu+p2fNr2i/ZXHHAMRDgatXbCGTulqyV/H5mJfn5+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T00:42:25Z"
    mac: ENC[AES256_GCM,data:4yYODBWS531uBLlbdNZ+Z1B/nbpsXwJoPvTfZ7A2SwKI/mTunrQdJMWlgEuo4W7qBs91wIcsYodrAnRqpQiihiTWPngGoaAHyk0Xj7vAAjHT+98v/WxFcEaykO/jiE3qkdoMooR7P6nvUnWzvS+dcp3sMnkzVASflMfW+3U8Pwg=,iv:kDEaRWD9wllD4vw1fbyesFkaR5YycDOFoRqzoSdfV/k=,tag:advk35b/aqMtHLwfk+JXRw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
