controller:
    private_key: ENC[AES256_GCM,data:f1Atmp4mIASR5PCzaK2Wn0CNENlSaF6Su4pDVk5fWTFisV6eZ3Dd94BR3Js=,iv:PacgN3SBG6T1FceZG+nCUeK6fvFy8m7S9gKj0FfIHNM=,tag:MZcP5be0s7v82D/YjwgJGA==,type:str]
    public_key: ENC[AES256_GCM,data:Bxy5x1LXKqdqoAVTQcXEuS0z1VLFosoVvk2TP67qUTvFC7A8V+iBlocmDmc=,iv:RWhMVrLxRjLNAG8cVri5KBQlJqMbnopAd8ULRFbYxjA=,tag:0S9oITjWDPNSG+U4TmTGpw==,type:str]
saconsole:
    private_key: ENC[AES256_GCM,data:JKtICmU9cK3q0d971cqeamItihn2NqkClg+m56nuqGDXW2Vld1TTgzYyvMs=,iv:FIIhT66Npc+nUXPFHubAuz2Z7elQW97U+Fq6suuYiTE=,tag:iENq4EmefBuop+xUVqQFcA==,type:str]
    public_key: ENC[AES256_GCM,data:wlHPFpQHwUpHoktjGqqgfJ24H/G89ab1XWQf6wnuZwtFkBQ/fSPJm89v6Ok=,iv:wphpwbLcDygXpKZWN4oetjkxuY+AlNXQJ27Ui1lYZ/E=,tag:1zMgLPOZFvLqmxUf9NZodw==,type:str]
dev03:
    private_key: ENC[AES256_GCM,data:er0UCCpncN+BdSAj7yBH2mcaw+mCbvkuu3D9OdjMSsLkBcbQKdnvo0YrFPs=,iv:8CPFjmd4vJoi+bKS0J8vph5wpezWrs1OlHTNKvC0xdw=,tag:7DSV/k9ibwmFYxeSpKXp2A==,type:str]
    public_key: ENC[AES256_GCM,data:RzDG/CrZdbGf2FIlA9UtXGuNjbcetzIs766BO8UPV8DP1luv4dJJHZmFROQ=,iv:qWKQZTH3Z89eGOOXHqERHjBXMEyyd6Y5KxtoZNHObRI=,tag:t97+i4AFNgBPQVwzJjH+Kw==,type:str]
dev01:
    private_key: ENC[AES256_GCM,data:vzP4St9D2nHeGHx/QyvIHvFgOZjAKfNWTlr+X+cZfjNFPjR7twXhuG5SGKY=,iv:yBsLDmee8QCqL0ZqtZlf3SIJnTE3IFymzxg2vdGXeGo=,tag:ok6S9mhgS8YtYMsuZ56Owg==,type:str]
    public_key: ENC[AES256_GCM,data:15DGBUAzTkqmbLH0EtyPqAGFz1bXtPYOjV64pduDptD0pBfvgm3dhzZm+7w=,iv:8ry5hhxPQ5oLc7H0mphkCqilF2qislJvHtlXnsnTRDM=,tag:2/xMyzyRXHy4fzcBHhjIRA==,type:str]
dev02:
    private_key: ENC[AES256_GCM,data:yjeYoRGmyZxB1kgxAYb0X8qFGOggjDe5tROvMpv2zpZ5q+xL/KkLhY7NaGc=,iv:kgCy1GhqK5W5JFC1H7d/LSLjyirZKA+x677JBl/z57E=,tag:qs7ftslKYwCnQZM4sbKy4w==,type:str]
    public_key: ENC[AES256_GCM,data:FmUZflTkuwUGhHthe1ztT+94MQTrt3o8UjD+SuZ8FZR5vcSkQr5tqRpGzbg=,iv:4G6UvbPdkUrcMQmVxsqaGEXcfaHI0LKPXxG1OA2pm3s=,tag:jqSHb7Acizt/BRZtaReKLQ==,type:str]
preshared_keys:
    controller_saconsole: ENC[AES256_GCM,data:yMdjuzjP6d8cGdm0mUDNLgMX6t0Et8YEdKBUy+vq5aDRnM7IfU+If3T/B9I=,iv:ry3thTDx+Ok12GBMAnIUeS3VvLbB2trrfhnC5v2fV1A=,tag:CmWjCwG+DCa8rIvj1pg4oA==,type:str]
    dev03_saconsole: ENC[AES256_GCM,data:CARTx2h2eZaHfxtz8rRPPccu7naPUPCLFHO8Sb45vvAqM21vyEJ8UDGotQ4=,iv:NuoGvFAS3l57fVND0yPbFsSl87KjKzEMw87QgJdTVmg=,tag:nubcSGcIDoYUwu7fAmIVcw==,type:str]
    dev01_saconsole: ENC[AES256_GCM,data:T8UDy9d/GLoUb+VSxpCSnRPvKIKftvxNSBsKqNCT8phtxpt/aJWLYvkrb0E=,iv:hdIJDHC80tiv1FwH4inVnqd7BfCvVTqB9fSNobkwOtw=,tag:n4YhLwAsJg/vzK/WiAQmwA==,type:str]
    dev02_saconsole: ENC[AES256_GCM,data:tl7OlH6//UKin6IV4lKd/qr0NfNzVEqu/cytRbfMj2Z/KSG2lOsULTE3lTk=,iv:0wxlBr2B7akJ+gCOiVQ17NH7jItspBr0Aab1ixU7XAY=,tag:I1c2YzBBqApRPKOf3uANKw==,type:str]
sops:
    age:
        - recipient: age185wy6suru3x53leqjf866zsz02vece8cnsy6g92tz7ae0ykw45dsjp2sl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIN3c1L2kyd2VvV1VzV1k0
            WjFNSldhWU43K1h5LzJHbUNSNjZvejQ1Y3dBCk1ET0g5b3Ria0g3azU3dHBIaTQ2
            RDFNa0JQcDYwbHFjTnVySWdobnVLVFUKLS0tIEtMWWtWbmNZVEpNNGRaZjM5NWdN
            OGVFT2pmM0poRzRLQzU5SllMVy94bk0Kitcx4dPyHXg3AwULlpnwOfHJmwTNRuxr
            91JKH4bRKT3vY3m+RrvVp0sdBnilb+nGrEuwyisKDRXFj5AklJDI6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T12:45:58Z"
    mac: ENC[AES256_GCM,data:I+sJEDXLM+gQXMmnS7+g2UF1Qzkh+81CuqLiYCW8ju14gEMDK/tDnMQCwq1Loofu7+JSpPsfSOoK6VI4gTyHsIWqtyv5zxD1E+N0mLS57DWKhBdIKuH2hadOyHB18HzHXcss61QeCAdp2qNdplVHUZVaieaciJIbpZXeoIJsDuU=,iv:KmifWLgwN+w5yASGCA8phf454Bt4gb3dcj6Nh54xMQg=,tag:Cch/kRLXT4LTjTXj6sPzlQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
