erp_user_pwd: ENC[AES256_GCM,data:OAqmhg==,iv:pVYd52TC5u3Q9xDOfrNt86ZDSIXDwYbL8aael9ta36A=,tag:ioqgGyMGWTsIEDEUUpJeaA==,type:str]
db_root_pwd: ENC[AES256_GCM,data:LR23BTXmXbgVwl6/UA==,iv:Q+j9bQ4xdMXc/jQWtk/eFteCkrABs9oHs3JBHqWVDvc=,tag:jzAZ6CC3yUOtWp4yIcK3EA==,type:str]
sops:
    age:
        - recipient: age185wy6suru3x53leqjf866zsz02vece8cnsy6g92tz7ae0ykw45dsjp2sl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dEFsZU15dTlDRDFQekZM
            VXJwNjZDdng2R3BmNk9nYjY3U2ZMMG1SNnhzCm1oS0wvSzllTUE4LzFLdHM5YVNi
            MFVuOHVMQjlnK3FmZVVkazlaT0tJMkEKLS0tIFF0TndLN1R2SkhjTTBMTjNiWGdh
            cEltNE5mdThWTlM4TkZ1NXVwR0dSR2sK23bjVU24/BkahzdVJ7srlNMjJe1q8PGt
            tr3n5z272bKh8WLZkMOfmAlGnGsBBoV8uzXXBzVpihUjgU2jxySaRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T21:26:14Z"
    mac: ENC[AES256_GCM,data:sZnKlwMuAxVeMAeeIao37h3PZoNJW8ND75xk7dptHe+gAm/+e+E+KKM31UdRpg5+N73qtGwkjHbiJBjqCU+wA0/mJaEGxK/LPtniGjkNu14PPIAFKJ7GJRq3duIx7dazYKs3QPCOnv7i++6ke47HCrBEhp4mgJgbJSqab3N/MKU=,iv:RHU8lPidpAYo0TyGor9nOZwmZ9xPBY4dqeq0FvOm4kY=,tag:2iT1044DVT8OGgipr7Xcpg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
