#!/usr/bin/env bash
set -euo pipefail

BENCH_DIR_ORIG="/home/erpadm/frappe-bench"
BENCH_DIR="/home/erpadm/frappe-bench-D2IRBL"
SITE_URL="dev02.iridium.blue"
ERP_USER="erpadm"
MYPWD="erpnext_build"
ERP_USER_PWD="sasa"

pip3 install --quiet jinja2 2>/dev/null || true

echo "=== A: deploy pre-rendered envars.sh ==="
sudo mkdir -p /opt/ce_sri
sudo cp /tmp/rendered/envars.sh /opt/ce_sri/envars.sh
sudo chmod 644 /opt/ce_sri/envars.sh
echo "  [OK] /opt/ce_sri/envars.sh"

echo "=== A2: rename bench dir ==="
if sudo test -d "$BENCH_DIR_ORIG" && ! sudo test -L "$BENCH_DIR"; then
    sudo -u "$ERP_USER" ln -sf "$BENCH_DIR_ORIG" "$BENCH_DIR"
    echo "  [OK] symlinked frappe-bench -> frappe-bench-D2IRBL (venv paths preserved)"
elif sudo test -L "$BENCH_DIR"; then
    echo "  [OK] frappe-bench-D2IRBL symlink already exists — skipping"
else
    echo "  [ERROR] Neither $BENCH_DIR_ORIG nor $BENCH_DIR found"
    exit 1
fi

echo "=== A2b: deploy Procfile ==="
PROCFILE="$BENCH_DIR/Procfile"
if ! grep -q 'ce_sri_svc' "$PROCFILE" 2>/dev/null; then
  cp /tmp/rendered/Procfile "$PROCFILE"
  chown $ERP_USER:$ERP_USER "$PROCFILE"
  echo "  [OK] Procfile deployed"
else
  echo "  [OK] Procfile already contains ce_sri_svc — skipping"
fi

echo "=== A2c: setup deploy keys for GitHub ==="
mkdir -p /home/$ERP_USER/.ssh
chmod 700 /home/$ERP_USER/.ssh
for key in you_gh_ce_sri you_gh_ce_sri_svc you_gh_route_planner you_gh.txt; do
    if [ -f /tmp/$key ]; then
        mv /tmp/$key /home/$ERP_USER/.ssh/$key
        chmod 600 /home/$ERP_USER/.ssh/$key
    fi
done
cp /tmp/rendered/ssh_config /home/$ERP_USER/.ssh/config
chmod 600 /home/$ERP_USER/.ssh/config
cp /tmp/rendered/gh_askpass.sh /home/$ERP_USER/.ssh/gh_askpass.sh
chmod 700 /home/$ERP_USER/.ssh/gh_askpass.sh
chown -R $ERP_USER:$ERP_USER /home/$ERP_USER/.ssh
echo "  [OK] deploy keys + SSH config installed"

echo "=== A2d: clone apps from GitHub ==="
_GH_CLONE() {
  sudo -u "$ERP_USER" bash -c "
    export DISPLAY=:0
    export SSH_ASKPASS=/home/$ERP_USER/.ssh/gh_askpass.sh
    export SSH_ASKPASS_REQUIRE=force
    export GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no'
    $1
  "
}
if [ ! -d "$BENCH_DIR/apps/ce_sri/.git" ]; then
  _GH_CLONE "cd $BENCH_DIR && git clone git@ce_sri.gh:martinhbramwell/ce_sri.git apps/ce_sri --branch wip/2026-03-25"
  echo "  [OK] ce_sri cloned"
else
  _GH_CLONE "cd $BENCH_DIR/apps/ce_sri && git pull"
  echo "  [OK] ce_sri pulled"
fi
if [ ! -d "$BENCH_DIR/apps/route_planner/.git" ]; then
  _GH_CLONE "cd $BENCH_DIR && git clone git@route_planner.gh:martinhbramwell/route_planner.git apps/route_planner --branch wip/2026-03-31"
  echo "  [OK] route_planner cloned"
else
  _GH_CLONE "cd $BENCH_DIR/apps/route_planner && git pull"
  echo "  [OK] route_planner pulled"
fi
if [ ! -d "$BENCH_DIR/apps/returnable/.git" ]; then
  sudo -u "$ERP_USER" bash -c "cd $BENCH_DIR && git clone https://github.com/martinhbramwell/BtlMng.git apps/returnable --branch wip/2026-03-31"
  echo "  [OK] returnable (BtlMng) cloned"
else
  sudo -u "$ERP_USER" bash -c "cd $BENCH_DIR/apps/returnable && git pull"
  echo "  [OK] returnable pulled"
fi
if [ ! -d "$BENCH_DIR/apps/ce_sri/services/ce_sri_svc/.git" ]; then
  _GH_CLONE "mkdir -p $BENCH_DIR/apps/ce_sri/services && cd $BENCH_DIR && git clone git@ce_sri_svc.gh:martinhbramwell/ce_sri_svc.git apps/ce_sri/services/ce_sri_svc --branch wip/2026-03-31"
  echo "  [OK] ce_sri_svc cloned"
else
  _GH_CLONE "cd $BENCH_DIR/apps/ce_sri/services/ce_sri_svc && git pull"
  echo "  [OK] ce_sri_svc pulled"
fi
if [ ! -d "$BENCH_DIR/BaRe/.git" ]; then
  sudo -u "$ERP_USER" bash -c "cd $BENCH_DIR && git clone https://github.com/martinhbramwell/BaRe.git BaRe"
  echo "  [OK] BaRe cloned"
else
  sudo -u "$ERP_USER" bash -c "cd $BENCH_DIR/BaRe && git pull"
  echo "  [OK] BaRe pulled"
fi
echo "  [OK] all apps cloned/pulled from GitHub"

echo "=== A3: start bench services (supervisor) ==="
sudo -u "$ERP_USER" bash -c "cd $BENCH_DIR && bench setup supervisor --yes"
sudo cp "$BENCH_DIR/config/supervisor.conf" /etc/supervisor/conf.d/frappe-bench.conf
echo "=== A3b: deploy ce_sri_svc supervisor conf ==="
sudo cp /tmp/rendered/ce_sri_svc_supervisor.conf /etc/supervisor/conf.d/ce-sri-svc.conf
echo "  [OK] /etc/supervisor/conf.d/ce-sri-svc.conf deployed"
sudo supervisorctl reread
sudo supervisorctl update
sudo supervisorctl start all || true
echo "  Waiting 20s for Redis to be ready..."
sleep 20
echo "  [OK] bench services started"
sudo chmod o+x /home/"$ERP_USER"
echo "  [OK] /home/$ERP_USER world-traversable for nginx"

echo "=== B: fix ownership of BKP ==="
sudo chown -R "$ERP_USER:$ERP_USER" $BENCH_DIR/BKP
echo "  [OK] BKP ownership -> $ERP_USER"

echo "=== B2: (removed — .env generated by install.py before_install in H4c) ==="

echo "=== B2b: npm install for ce_sri_svc ==="
_CESRI_SVC="$BENCH_DIR/apps/ce_sri/services/ce_sri_svc"
if [ -f "$_CESRI_SVC/package.json" ]; then
  sudo -u "$ERP_USER" bash -c "cd $_CESRI_SVC && npm install 2>&1"
  echo "  [OK] npm install completed for ce_sri_svc"
else
  echo "  [SKIP] no package.json in ce_sri_svc"
fi

echo "=== C: BaRe/envars.sh symlink ==="
sudo -u "$ERP_USER" ln -sf /opt/ce_sri/envars.sh "$BENCH_DIR/BaRe/envars.sh"
echo "  [OK] BaRe/envars.sh -> /opt/ce_sri/envars.sh"

echo "=== D: bench new-site + install-app erpnext ==="
echo "  site: $SITE_URL  bench: $BENCH_DIR"
if sudo -u "$ERP_USER" bash -c "cd $BENCH_DIR && bench --site $SITE_URL doctor" 2>/dev/null; then
  echo "  [SKIP] site $SITE_URL already exists"
else
  sudo -u "$ERP_USER" bash -c "
    cd $BENCH_DIR
    bench new-site $SITE_URL \
      --mariadb-root-password $MYPWD \
      --admin-password $ERP_USER_PWD
    bench --site $SITE_URL install-app erpnext
  "
  echo "  [OK] site created, erpnext installed"
fi

echo "=== E: place ddlViews.sql ==="
sudo -u "$ERP_USER" mkdir -p "$BENCH_DIR/sites/$SITE_URL/private/files"
sudo -u "$ERP_USER" cp /tmp/ddlViews.sql "/home/erpadm/frappe-bench-D2IRBL/sites/dev02.iridium.blue/private/files/ddlViews.sql"
rm -f /tmp/ddlViews.sql
echo '  [OK] ddlViews.sql placed'

echo "=== F: installApps.sh ==="
sudo -u "$ERP_USER" bash -c "cd $BENCH_DIR && bash BaRe/installApps.sh"
echo "  [OK] installApps.sh complete"

echo "=== G-pre: strip DEFINER clauses from backup SQL ==="
python3 /tmp/vm_scripts/gpre_strip_definer.py --bench-dir "$BENCH_DIR"

echo "=== G: handleRestore.sh ==="
sudo -u "$ERP_USER" bash -c "cd $BENCH_DIR && bash BaRe/handleRestore.sh"
echo "  [OK] database restored"

echo "=== H: supervisor reload (post-restore) ==="
sudo supervisorctl reread
sudo supervisorctl update
echo "  [OK] supervisor updated"

echo "=== H2: bench restart ==="
sudo -u "$ERP_USER" bash -c "cd $BENCH_DIR && bench restart || true"
sudo supervisorctl restart frappe-bench-ce-sri-svc || true
echo "  [OK] bench + ce_sri_svc restarted"

echo "=== H3: reset admin password (bench restore overwrites it) ==="
sudo -u "$ERP_USER" bash -c "cd $BENCH_DIR && bench --site $SITE_URL set-admin-password $ERP_USER_PWD"
echo "  [OK] admin password reset to ERP_USER_PWD"

echo "=== H4a: clear stale encrypted secrets + regenerate API key ==="
sudo -u "$ERP_USER" bash -c "cd $BENCH_DIR && $BENCH_DIR/env/bin/python /tmp/vm_scripts/h4a_apikeys.py --site $SITE_URL --bench-dir $BENCH_DIR"

echo "=== H4b: place secrets for install.py ==="
sudo -u "$ERP_USER" mkdir -p /home/$ERP_USER/.ssh/secrets
for f in /tmp/*.p12 /tmp/ce_sri_parms_*.json /tmp/docType_Logo.png; do
  if [ -f "$f" ]; then
    DEST="/home/$ERP_USER/.ssh/secrets/$(basename "$f")"
    if [[ "$f" == *ce_sri_parms_*.json ]]; then
      DEST="/home/$ERP_USER/.ssh/secrets/ce_sri_parms.json"
    fi
    sudo mv "$f" "$DEST"
    sudo chown $ERP_USER:$ERP_USER "$DEST"
    sudo chmod 600 "$DEST"
    echo "  [OK] $(basename "$DEST") -> /home/$ERP_USER/.ssh/secrets/"
  fi
done

echo "=== H4c: generate bench nginx.conf (install.py patches it) ==="
sudo -u "$ERP_USER" bash -c "cd $BENCH_DIR && bench setup nginx --yes" || true
echo "  [OK] config/nginx.conf generated"

echo "=== H4d: run ce_sri before_install ==="
sudo -u "$ERP_USER" bash -c "cd $BENCH_DIR && bench --site $SITE_URL execute ce_sri.install.before_install"
echo "  [OK] ce_sri before_install complete"

echo "=== H4e: generate .env via UPDATE_SRI_SERVICE_PARAMETERS.py ==="
_CESRI_SVC="$BENCH_DIR/apps/ce_sri/services/ce_sri_svc"
python3 /tmp/vm_scripts/h4e_patch_parms.py \
  --apikey-sh "$BENCH_DIR/sites/$SITE_URL/private/files/apikey.sh" \
  --parms /home/$ERP_USER/.ssh/secrets/ce_sri_parms.json
sudo -u "$ERP_USER" bash -c "cd $_CESRI_SVC && python3 UPDATE_SRI_SERVICE_PARAMETERS.py --parms /home/$ERP_USER/.ssh/secrets/ce_sri_parms.json"
echo "  [OK] .env generated for $SITE_URL"

echo "=== H4f: restart after install.py + .env changes ==="
sudo supervisorctl reread
sudo supervisorctl update
sudo -u "$ERP_USER" bash -c "cd $BENCH_DIR && bench restart || true"
sudo supervisorctl restart frappe-bench-ce-sri-svc || true
sudo nginx -t && sudo systemctl reload nginx || true
echo "  [OK] services restarted after install.py"

echo "=== I: install TLS cert ==="
sudo mkdir -p /etc/nginx/certs/iridium.blue
if [ -f /tmp/fullchain.pem ]; then
  sudo cp /tmp/fullchain.pem /etc/nginx/certs/iridium.blue/fullchain.pem
  sudo cp /tmp/privkey.pem   /etc/nginx/certs/iridium.blue/privkey.pem
  sudo chmod 600 /etc/nginx/certs/iridium.blue/privkey.pem
  sudo rm -f /tmp/fullchain.pem /tmp/privkey.pem /tmp/cert.pem
  echo "  [OK] certs installed to /etc/nginx/certs/iridium.blue"
elif [ -f /etc/nginx/certs/iridium.blue/fullchain.pem ]; then
  echo "  [OK] certs already in place at /etc/nginx/certs/iridium.blue — skipping"
else
  echo "  [ERROR] no cert at /tmp/fullchain.pem and none at /etc/nginx/certs/iridium.blue"
  exit 1
fi

echo "=== J: deploy nginx vhost config ==="
sudo cp /tmp/rendered/nginx_vhost.conf /etc/nginx/sites-available/dev02.iridium.blue
echo "  [OK] /etc/nginx/sites-available/dev02.iridium.blue"

echo "=== K: DH params + enable site ==="
if [ ! -f /etc/nginx/dhparam.pem ]; then
    echo "  Generating DH params (2048-bit) — once per VM, reused on redeploy ..."
    sudo openssl dhparam -out /etc/nginx/dhparam.pem 2048 2>/dev/null
    echo "  [OK] DH params written to /etc/nginx/dhparam.pem"
fi
sudo ln -sf /etc/nginx/sites-available/dev02.iridium.blue /etc/nginx/sites-enabled/dev02.iridium.blue
sudo rm -f /etc/nginx/sites-enabled/default
sudo nginx -t && sudo systemctl reload nginx
echo "  [OK] nginx reloaded with SSL site"

echo "=== L0: deploy stop.py ==="
cp /tmp/rendered/stop.py $BENCH_DIR/stop.py
chown $ERP_USER:$ERP_USER $BENCH_DIR/stop.py
chmod 755 $BENCH_DIR/stop.py
echo "  [OK] stop.py deployed to $BENCH_DIR"

echo "=== L: render bash_aliases (VM-side — needs DB_NAME from site_config.json) ==="
DB_NAME=$(python3 -c "import json; print(json.load(open('$BENCH_DIR/sites/$SITE_URL/site_config.json'))['db_name'])" 2>/dev/null || echo "unknown_db")
python3 /tmp/renderers/render_bash_aliases.py \
  --template /tmp/templates/bash_aliases.j2 \
  --params /tmp/rendered/params.json \
  --output /home/$ERP_USER/.bash_aliases \
  --extra db_name="$DB_NAME"
chown $ERP_USER:$ERP_USER /home/$ERP_USER/.bash_aliases
echo "  [OK] .bash_aliases rendered for $ERP_USER"

echo "=== Done ==="
