#!/usr/bin/env python3
"""
generate_inventory.py — Derive Ansible inventory from hosts_map.yml

Reads hosts_map.yml at the project root and writes:
  ansible/inventory/kvm.yml  — Ansible inventory for all ansible_managed hosts

Also prints the WireGuard peer summary (public keys must be in
ansible/group_vars/kvm.yml separately after running config/wireguard/generate_keys.sh).

Usage (from project root):
    python tools/generate_inventory.py

The generated inventory file carries a header warning against direct editing.
"""

import sys
import os
import yaml
from pathlib import Path

PROJ_ROOT = Path(__file__).parent.parent
HOSTS_MAP  = PROJ_ROOT / "hosts_map.yml"
KVM_INV    = PROJ_ROOT / "ansible" / "inventory" / "kvm.yml"

# Only hosts with this backend (or no backend field) are included in kvm.yml.
KVM_BACKEND = "kvm"


def load_hosts_map() -> dict:
    with open(HOSTS_MAP) as f:
        return yaml.safe_load(f)


def build_inventory(data: dict) -> dict:
    """Build an Ansible inventory dict from hosts_map.yml."""

    # Collect all ansible_managed hosts and their group memberships
    group_members: dict[str, list[str]] = {}   # group_name → [hostname, ...]
    host_vars: dict[str, dict] = {}            # hostname → host vars

    for _section, hosts in data.get("groups", {}).items():
        if not hosts:
            continue
        for logical_name, attrs in hosts.items():
            if not attrs.get("ansible_managed", False):
                continue
            # kvm.yml only includes KVM-backend hosts; vbox/cloudstack hosts
            # have their own inventories and must not pollute this file.
            if attrs.get("backend", KVM_BACKEND) != KVM_BACKEND:
                continue

            hostname = attrs["hostname"]
            # Only host-specific vars here; connection settings (ansible_user,
            # ansible_ssh_private_key_file, etc.) live in group_vars/kvm.yml
            # so they are not duplicated or overridden with placeholders.
            # ansible_connection is included when explicitly set (e.g. "local" for controller).
            hv = {
                "ansible_host": attrs.get("virbr0_ip", attrs["hostname"]),
                "wg_ip":        attrs.get("wg_ip"),
                "wg_role":      attrs.get("wg_role"),
            }
            if attrs.get("ansible_connection"):
                hv["ansible_connection"] = attrs["ansible_connection"]
            host_vars[hostname] = hv

            for grp in attrs.get("ansible_groups", []):
                group_members.setdefault(grp, []).append(hostname)

    # Build inventory structure
    inventory: dict = {"all": {"children": {}}}

    for grp, members in group_members.items():
        hosts_dict = {}
        for h in members:
            hosts_dict[h] = host_vars.get(h, {})
        inventory["all"]["children"][grp] = {"hosts": hosts_dict}

    return inventory


def wireguard_peer_summary(data: dict) -> None:
    """Print a summary of all WireGuard peers (including non-Ansible hosts)."""
    print("\nWireGuard peer summary (all hosts, including non-Ansible):")
    print(f"  Subnet: {data.get('wireguard_subnet')}  Port: {data.get('wireguard_port')}")
    print()
    for _section, hosts in data.get("groups", {}).items():
        if not hosts:
            continue
        for logical_name, attrs in hosts.items():
            managed = "ansible" if attrs.get("ansible_managed") else "manual "
            print(f"  {attrs['wg_role']:5s}  {attrs['wg_ip']:14s}  {attrs['hostname']:20s}  [{managed}]")
    print()


def main() -> None:
    if not HOSTS_MAP.exists():
        print(f"ERROR: {HOSTS_MAP} not found.", file=sys.stderr)
        sys.exit(1)

    data = load_hosts_map()
    inventory = build_inventory(data)

    KVM_INV.parent.mkdir(parents=True, exist_ok=True)

    header = (
        "# ansible/inventory/kvm.yml\n"
        "# AUTO-GENERATED by tools/generate_inventory.py — do not edit directly.\n"
        "# Edit hosts_map.yml at the project root, then re-run generate_inventory.py.\n\n"
    )

    with open(KVM_INV, "w") as f:
        f.write(header)
        yaml.dump(inventory, f, default_flow_style=False, sort_keys=False)

    print(f"✅  Written: {KVM_INV}")
    wireguard_peer_summary(data)
    print("Next: verify ansible/group_vars/kvm.yml has the correct wg_pubkey_* values")
    print("      (from the output of config/wireguard/generate_keys.sh)")


if __name__ == "__main__":
    main()
